
# basic information
title: Maom Lab
email: your-email@domain.com
description: Computational pharmacology lab of Matthew O'Meara at the Univerity of Michigan
twitter_username: momeara
github_username:  momeara

# site configuration
theme: jekyll-theme-minimal

