
# basic information
title: Maom Lab
email: your-email@domain.com
description: >- # ignore newlines until next tag
  Computational pharmacology lab of Matthew O'Meara<br>Univerity of Michigan
twitter_username: momeara
github_username:  momeara
baseurl: ""
url: "https://maomlab.github.io/" 

# site configuration
theme: jekyll-theme-minimal

github:
  repository_url: https://github.com/maomlab/maomlab.github.io
  is_project_page: false

plugins:
  - "jekyll-github-metadata"